version: '3.8'

services:
  osrm:
    image: osrm/osrm-backend:latest
    container_name: osrm-backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    command: >
      osrm-routed --algorithm mld /data/netherlands-latest.osrm
